// <auto-generated />
using System;
using Kalkulator.Infrastructure.Persistenz;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kalkulator.Infrastructure.Persistenz.Migrationen
{
    [DbContext(typeof(KalkulatorDbContext))]
    [Migration("20260925155119_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kalkulator.Domain.Katalog.BundleBestandteil", b =>
                {
                    b.Property<int>("BundleId")
                        .HasColumnType("int");

                    b.Property<int>("BestandteilId")
                        .HasColumnType("int");

                    b.HasKey("BundleId", "BestandteilId");

                    b.HasIndex("BestandteilId");

                    b.ToTable("BundleBestandteile", "katalog", t =>
                        {
                            t.HasCheckConstraint("CK_BundleBestandteile_NichtSichSelbst", "[BundleId] <> [BestandteilId]");
                        });
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.DokumentVorlage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Dateiname")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version")
                        .IsUnique();

                    b.ToTable("DokumentVorlagen", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Preiskomponente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrechnungsart")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<string>("StaffelBezug")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("Preiskomponenten", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Kurzbeschreibung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("LeistungsscheinId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceNummer")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vertriebsstatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("KategorieId");

                    b.HasIndex("LeistungsscheinId");

                    b.ToTable("Services", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceKategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Kategorien", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Meldung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Regeln", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegelZiel", b =>
                {
                    b.Property<int>("RegelId")
                        .HasColumnType("int");

                    b.Property<int>("ZielServiceId")
                        .HasColumnType("int");

                    b.HasKey("RegelId", "ZielServiceId");

                    b.HasIndex("ZielServiceId");

                    b.ToTable("RegelZiele", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.EkPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anmerkung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("AufwandMinuten")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("AusBestandteilen")
                        .HasColumnType("bit");

                    b.Property<decimal?>("BetriebFix")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("EkLizenz")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("KostenKorrektur")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Overhead")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("PreiskomponenteId")
                        .HasColumnType("int");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreiskomponenteId");

                    b.HasIndex("PreislisteId", "PreiskomponenteId")
                        .IsUnique();

                    b.ToTable("EkPositionen", "intern");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<string>("Schluessel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Wert")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)");

                    b.HasKey("Id");

                    b.HasIndex("PreislisteId", "Schluessel")
                        .IsUnique();

                    b.ToTable("Parameter", "preise");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PreiskomponenteId")
                        .HasColumnType("int");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VkNetto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PreiskomponenteId");

                    b.HasIndex("PreislisteId", "PreiskomponenteId")
                        .IsUnique();

                    b.ToTable("Preise", "preise");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FreigegebenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FreigegebenVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("VorgaengerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Bezeichnung")
                        .IsUnique();

                    b.HasIndex("VorgaengerId");

                    b.ToTable("Preislisten", "preise");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisstaffel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbMenge")
                        .HasColumnType("int");

                    b.Property<int>("PreiskomponenteId")
                        .HasColumnType("int");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VkNetto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PreiskomponenteId");

                    b.HasIndex("PreislisteId", "PreiskomponenteId", "AbMenge")
                        .IsUnique();

                    b.ToTable("Preisstaffeln", "preise", t =>
                        {
                            t.HasCheckConstraint("CK_Preisstaffeln_AbMenge", "[AbMenge] >= 0");
                        });
                });

            modelBuilder.Entity("Kalkulator.Infrastructure.Persistenz.AenderungsEintrag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aenderungen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Benutzer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Entitaet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Schluessel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Zeitpunkt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Zeitpunkt");

                    b.HasIndex("Entitaet", "Schluessel");

                    b.ToTable("Aenderungsprotokoll", "protokoll");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.BundleBestandteil", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Service", "Bestandteil")
                        .WithMany()
                        .HasForeignKey("BestandteilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Katalog.Service", "Bundle")
                        .WithMany("Bestandteile")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestandteil");

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Preiskomponente", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Service", "Service")
                        .WithMany("Preiskomponenten")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Service", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.ServiceKategorie", "Kategorie")
                        .WithMany()
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Katalog.DokumentVorlage", "Leistungsschein")
                        .WithMany()
                        .HasForeignKey("LeistungsscheinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kategorie");

                    b.Navigation("Leistungsschein");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegel", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Service", "Service")
                        .WithMany("Regeln")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegelZiel", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.ServiceRegel", null)
                        .WithMany("Ziele")
                        .HasForeignKey("RegelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Katalog.Service", "ZielService")
                        .WithMany()
                        .HasForeignKey("ZielServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ZielService");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.EkPosition", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Preiskomponente", null)
                        .WithMany()
                        .HasForeignKey("PreiskomponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany("EkPositionen")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Parameter", b =>
                {
                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany("Parameter")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preis", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Preiskomponente", null)
                        .WithMany()
                        .HasForeignKey("PreiskomponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany("Preise")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisliste", b =>
                {
                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany()
                        .HasForeignKey("VorgaengerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisstaffel", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Preiskomponente", null)
                        .WithMany()
                        .HasForeignKey("PreiskomponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany("Staffeln")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Service", b =>
                {
                    b.Navigation("Bestandteile");

                    b.Navigation("Preiskomponenten");

                    b.Navigation("Regeln");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegel", b =>
                {
                    b.Navigation("Ziele");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisliste", b =>
                {
                    b.Navigation("EkPositionen");

                    b.Navigation("Parameter");

                    b.Navigation("Preise");

                    b.Navigation("Staffeln");
                });
#pragma warning restore 612, 618
        }
    }
}
