// <auto-generated />
using System;
using Kalkulator.Infrastructure.Persistenz;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kalkulator.Infrastructure.Persistenz.Migrationen
{
    [DbContext(typeof(KalkulatorDbContext))]
    [Migration("20261004153722_PaperlessUebergabe")]
    partial class PaperlessUebergabe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kalkulator.Domain.Katalog.BundleBestandteil", b =>
                {
                    b.Property<int>("BundleId")
                        .HasColumnType("int");

                    b.Property<int>("BestandteilId")
                        .HasColumnType("int");

                    b.HasKey("BundleId", "BestandteilId");

                    b.HasIndex("BestandteilId");

                    b.ToTable("BundleBestandteile", "katalog", t =>
                        {
                            t.HasCheckConstraint("CK_BundleBestandteile_NichtSichSelbst", "[BundleId] <> [BestandteilId]");
                        });
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.DokumentVorlage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Dateiname")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DokumentVorlagen", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Preiskomponente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrechnungsart")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NavisionArtikelnummer")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<string>("StaffelBezug")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ServiceId");

                    b.ToTable("Preiskomponenten", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Kurzbeschreibung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("LeistungsscheinId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceNummer")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Vertriebsstatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("KategorieId");

                    b.HasIndex("LeistungsscheinId");

                    b.ToTable("Services", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceKategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sortierung")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Kategorien", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Meldung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Regeln", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegelZiel", b =>
                {
                    b.Property<int>("RegelId")
                        .HasColumnType("int");

                    b.Property<int>("ZielServiceId")
                        .HasColumnType("int");

                    b.HasKey("RegelId", "ZielServiceId");

                    b.HasIndex("ZielServiceId");

                    b.ToTable("RegelZiele", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.VorlagenDatei", b =>
                {
                    b.Property<int>("VorlagenversionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Inhalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("VorlagenversionId");

                    b.ToTable("VorlagenDateien", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Vorlagenabgleich", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AusgeloestVon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("Beginn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Bericht")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dateien")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Ende")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Fehler")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NeueFassungen")
                        .HasColumnType("int");

                    b.Property<string>("Quelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Beginn");

                    b.ToTable("Vorlagenabgleiche", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Vorlagenversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AbgerufenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AbgerufenVon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("DokumentVorlageId")
                        .HasColumnType("int");

                    b.Property<string>("Eingaben")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EntschiedenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntschiedenVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("GeaendertInQuelleAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GeaendertInQuelleVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Hinweise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Komponenten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.Property<string>("Pfad")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("QuellId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuellStand")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Quelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unterschriften")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionLaut")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DokumentVorlageId", "Nummer")
                        .IsUnique();

                    b.ToTable("Vorlagenversionen", "katalog");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.EkPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anmerkung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("AufwandMinuten")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("AusBestandteilen")
                        .HasColumnType("bit");

                    b.Property<decimal?>("BetriebFix")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("EkLizenz")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("KostenKorrektur")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Overhead")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("PreiskomponenteId")
                        .HasColumnType("int");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreiskomponenteId");

                    b.HasIndex("PreislisteId", "PreiskomponenteId")
                        .IsUnique();

                    b.ToTable("EkPositionen", "intern");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<string>("Schluessel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Wert")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)");

                    b.HasKey("Id");

                    b.HasIndex("PreislisteId", "Schluessel")
                        .IsUnique();

                    b.ToTable("Parameter", "preise");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PreiskomponenteId")
                        .HasColumnType("int");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VkNetto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PreiskomponenteId");

                    b.HasIndex("PreislisteId", "PreiskomponenteId")
                        .IsUnique();

                    b.ToTable("Preise", "preise");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FreigegebenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FreigegebenVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("GueltigAb")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("VorgaengerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Bezeichnung")
                        .IsUnique();

                    b.HasIndex("VorgaengerId");

                    b.ToTable("Preislisten", "preise");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisstaffel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbMenge")
                        .HasColumnType("int");

                    b.Property<string>("Bezeichnung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NavisionArtikelnummer")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PreiskomponenteId")
                        .HasColumnType("int");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VkNetto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("PreiskomponenteId");

                    b.HasIndex("PreislisteId", "PreiskomponenteId", "AbMenge")
                        .IsUnique();

                    b.ToTable("Preisstaffeln", "preise", t =>
                        {
                            t.HasCheckConstraint("CK_Preisstaffeln_AbMenge", "[AbMenge] >= 0");
                        });
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Angebot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Freitext")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateOnly>("GueltigBis")
                        .HasColumnType("date");

                    b.Property<int>("KalkulationsversionId")
                        .HasColumnType("int");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("VersendetAm")
                        .HasColumnType("date");

                    b.Property<string>("VersendetVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Vorlage")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("KalkulationsversionId")
                        .IsUnique();

                    b.HasIndex("Nummer");

                    b.ToTable("Angebote", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.AngebotsDatei", b =>
                {
                    b.Property<int>("AngebotId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Inhalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AngebotId");

                    b.ToTable("AngebotsDateien", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kalkulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Angebotsnummer")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Eingabe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("FuerForecast")
                        .HasColumnType("bit");

                    b.Property<int>("KundenprojektId")
                        .HasColumnType("int");

                    b.Property<int>("LetzteVersionsnummer")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Vertragsangaben")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Vertragsbeginn")
                        .HasColumnType("date");

                    b.Property<byte[]>("Zeilenversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Angebotsnummer")
                        .IsUnique()
                        .HasFilter("[Angebotsnummer] IS NOT NULL");

                    b.HasIndex("KundenprojektId")
                        .IsUnique()
                        .HasDatabaseName("IX_Kalkulationen_Forecast")
                        .HasFilter("[FuerForecast] = 1");

                    b.ToTable("Kalkulationen", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kalkulationsversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Eingabe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("FreigabeSolutionConsultantAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FreigabeSolutionConsultantVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("FreigabeVertriebsleitungAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FreigabeVertriebsleitungVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KalkulationId")
                        .HasColumnType("int");

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.Property<int>("PreislisteId")
                        .HasColumnType("int");

                    b.Property<decimal>("SummeEinmalig")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SummeMonatlich")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Vertragsangaben")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Vertragsbeginn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PreislisteId");

                    b.HasIndex("KalkulationId", "Nummer")
                        .IsUnique();

                    b.ToTable("Kalkulationsversionen", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ansprechpartner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NavisionKundennummer")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ort")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Postleitzahl")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Strasse")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("NavisionKundennummer")
                        .IsUnique()
                        .HasFilter("[NavisionKundennummer] IS NOT NULL");

                    b.ToTable("Kunden", "projekte");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kundenprojekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AngelegtAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AngelegtVon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("AngenommenesAngebotId")
                        .HasColumnType("int");

                    b.Property<bool>("Bestandskunde")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("ErwarteterAbschlussmonat")
                        .HasColumnType("date");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Verantwortlich")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Verlustgrund")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Wahrscheinlichkeit")
                        .HasColumnType("int");

                    b.Property<byte[]>("Zeilenversion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AngenommenesAngebotId");

                    b.HasIndex("KundeId");

                    b.HasIndex("Status");

                    b.ToTable("Kundenprojekte", "projekte", t =>
                        {
                            t.HasCheckConstraint("CK_Kundenprojekte_Wahrscheinlichkeit", "[Wahrscheinlichkeit] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Nummernkreis", b =>
                {
                    b.Property<string>("Kreis")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Jahr")
                        .HasColumnType("int");

                    b.Property<int>("LetzteNummer")
                        .HasColumnType("int");

                    b.HasKey("Kreis", "Jahr");

                    b.ToTable("Nummernkreise", "projekte");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.PositionsKosten", b =>
                {
                    b.Property<int>("VersionsPositionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Kosten")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("VersionsPositionId");

                    b.ToTable("PositionsKosten", "intern");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Sonderposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Begruendung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Einmalig")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("EntschiedenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntschiedenVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KalkulationId")
                        .HasColumnType("int");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.Property<decimal>("Preis")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("KalkulationId");

                    b.ToTable("Sonderpositionen", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.StatusEreignis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Benutzer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("KundenprojektId")
                        .HasColumnType("int");

                    b.Property<string>("Neu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Verlustgrund")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("Zeitpunkt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("KundenprojektId", "Zeitpunkt");

                    b.ToTable("StatusEreignisse", "projekte");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.VersionsPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abrechnungsart")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("BerechneteMenge")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Betrag")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Einzelpreis")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Herkunft")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Hinweis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("KalkulationsversionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Menge")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<string>("ServiceCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCode");

                    b.HasIndex("KalkulationsversionId", "Reihenfolge")
                        .IsUnique();

                    b.ToTable("VersionsPositionen", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Vertragswerk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AngebotId")
                        .HasColumnType("int");

                    b.Property<int>("Ausfertigung")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ErstelltAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GesamtDateiname")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("KundenprojektId")
                        .HasColumnType("int");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaperlessDokumentId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UebergabeFehler")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("UebergabeVersuchtAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UebergebenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Unterzeichner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipDateiname")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("AngebotId");

                    b.HasIndex("KundenprojektId", "Ausfertigung")
                        .IsUnique();

                    b.ToTable("Vertragswerke", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.VertragswerkDatei", b =>
                {
                    b.Property<int>("VertragswerkId")
                        .HasColumnType("int");

                    b.Property<byte[]>("GesamtPdf")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Zip")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("VertragswerkId");

                    b.ToTable("VertragswerkDateien", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.VertragswerkEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Fassung")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<int>("VertragswerkId")
                        .HasColumnType("int");

                    b.Property<int>("VorlagenversionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VertragswerkId");

                    b.HasIndex("VorlagenversionId");

                    b.ToTable("VertragswerkDokumente", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Vertriebsfreigabe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AufgehobenAm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AufgehobenVon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Aufhebungsgrund")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Benutzer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KalkulationId")
                        .HasColumnType("int");

                    b.Property<string>("Kommentar")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Rolle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("Zeitpunkt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("KalkulationId", "Rolle")
                        .IsUnique()
                        .HasDatabaseName("IX_Vertriebsfreigaben_Aktiv")
                        .HasFilter("[AufgehobenAm] IS NULL");

                    b.ToTable("Vertriebsfreigaben", "kalkulation");
                });

            modelBuilder.Entity("Kalkulator.Infrastructure.Persistenz.AenderungsEintrag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Aenderungen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aktion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Benutzer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Entitaet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Schluessel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Zeitpunkt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Zeitpunkt");

                    b.HasIndex("Entitaet", "Schluessel");

                    b.ToTable("Aenderungsprotokoll", "protokoll");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.BundleBestandteil", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Service", "Bestandteil")
                        .WithMany()
                        .HasForeignKey("BestandteilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Katalog.Service", "Bundle")
                        .WithMany("Bestandteile")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestandteil");

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Preiskomponente", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Service", "Service")
                        .WithMany("Preiskomponenten")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Service", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.ServiceKategorie", "Kategorie")
                        .WithMany()
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Katalog.DokumentVorlage", "Leistungsschein")
                        .WithMany()
                        .HasForeignKey("LeistungsscheinId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kategorie");

                    b.Navigation("Leistungsschein");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegel", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Service", "Service")
                        .WithMany("Regeln")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegelZiel", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.ServiceRegel", null)
                        .WithMany("Ziele")
                        .HasForeignKey("RegelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Katalog.Service", "ZielService")
                        .WithMany()
                        .HasForeignKey("ZielServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ZielService");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.VorlagenDatei", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Vorlagenversion", null)
                        .WithOne("Datei")
                        .HasForeignKey("Kalkulator.Domain.Katalog.VorlagenDatei", "VorlagenversionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Vorlagenversion", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.DokumentVorlage", null)
                        .WithMany("Versionen")
                        .HasForeignKey("DokumentVorlageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.EkPosition", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Preiskomponente", "Preiskomponente")
                        .WithMany()
                        .HasForeignKey("PreiskomponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany("EkPositionen")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preiskomponente");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Parameter", b =>
                {
                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany("Parameter")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preis", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Preiskomponente", "Preiskomponente")
                        .WithMany()
                        .HasForeignKey("PreiskomponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany("Preise")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preiskomponente");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisliste", b =>
                {
                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany()
                        .HasForeignKey("VorgaengerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisstaffel", b =>
                {
                    b.HasOne("Kalkulator.Domain.Katalog.Preiskomponente", "Preiskomponente")
                        .WithMany()
                        .HasForeignKey("PreiskomponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany("Staffeln")
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preiskomponente");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Angebot", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Kalkulationsversion", "Version")
                        .WithMany()
                        .HasForeignKey("KalkulationsversionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.AngebotsDatei", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Angebot", null)
                        .WithOne("Datei")
                        .HasForeignKey("Kalkulator.Domain.Projekte.AngebotsDatei", "AngebotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kalkulation", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Kundenprojekt", "Kundenprojekt")
                        .WithMany("Kalkulationen")
                        .HasForeignKey("KundenprojektId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kundenprojekt");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kalkulationsversion", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Kalkulation", null)
                        .WithMany("Versionen")
                        .HasForeignKey("KalkulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Preise.Preisliste", null)
                        .WithMany()
                        .HasForeignKey("PreislisteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kundenprojekt", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Angebot", null)
                        .WithMany()
                        .HasForeignKey("AngenommenesAngebotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kalkulator.Domain.Projekte.Kunde", "Kunde")
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.PositionsKosten", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.VersionsPosition", null)
                        .WithOne("Kosten")
                        .HasForeignKey("Kalkulator.Domain.Projekte.PositionsKosten", "VersionsPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Sonderposition", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Kalkulation", null)
                        .WithMany("Sonderpositionen")
                        .HasForeignKey("KalkulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.StatusEreignis", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Kundenprojekt", null)
                        .WithMany("StatusEreignisse")
                        .HasForeignKey("KundenprojektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.VersionsPosition", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Kalkulationsversion", null)
                        .WithMany("Positionen")
                        .HasForeignKey("KalkulationsversionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Vertragswerk", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Angebot", null)
                        .WithMany()
                        .HasForeignKey("AngebotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Projekte.Kundenprojekt", null)
                        .WithMany()
                        .HasForeignKey("KundenprojektId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.VertragswerkDatei", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Vertragswerk", null)
                        .WithOne("Datei")
                        .HasForeignKey("Kalkulator.Domain.Projekte.VertragswerkDatei", "VertragswerkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.VertragswerkEintrag", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Vertragswerk", null)
                        .WithMany("Dokumente")
                        .HasForeignKey("VertragswerkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kalkulator.Domain.Katalog.Vorlagenversion", null)
                        .WithMany()
                        .HasForeignKey("VorlagenversionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Vertriebsfreigabe", b =>
                {
                    b.HasOne("Kalkulator.Domain.Projekte.Kalkulation", null)
                        .WithMany("Vertriebsfreigaben")
                        .HasForeignKey("KalkulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.DokumentVorlage", b =>
                {
                    b.Navigation("Versionen");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Service", b =>
                {
                    b.Navigation("Bestandteile");

                    b.Navigation("Preiskomponenten");

                    b.Navigation("Regeln");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.ServiceRegel", b =>
                {
                    b.Navigation("Ziele");
                });

            modelBuilder.Entity("Kalkulator.Domain.Katalog.Vorlagenversion", b =>
                {
                    b.Navigation("Datei");
                });

            modelBuilder.Entity("Kalkulator.Domain.Preise.Preisliste", b =>
                {
                    b.Navigation("EkPositionen");

                    b.Navigation("Parameter");

                    b.Navigation("Preise");

                    b.Navigation("Staffeln");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Angebot", b =>
                {
                    b.Navigation("Datei");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kalkulation", b =>
                {
                    b.Navigation("Sonderpositionen");

                    b.Navigation("Versionen");

                    b.Navigation("Vertriebsfreigaben");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kalkulationsversion", b =>
                {
                    b.Navigation("Positionen");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Kundenprojekt", b =>
                {
                    b.Navigation("Kalkulationen");

                    b.Navigation("StatusEreignisse");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.VersionsPosition", b =>
                {
                    b.Navigation("Kosten");
                });

            modelBuilder.Entity("Kalkulator.Domain.Projekte.Vertragswerk", b =>
                {
                    b.Navigation("Datei");

                    b.Navigation("Dokumente");
                });
#pragma warning restore 612, 618
        }
    }
}
